---
# Website Configuration
current_website_url: "http://localhost:8000"
industry: "Professional Services"
target_audience: "Business professionals and potential clients"
brand_guidelines:
  primary_colors:
    - "#2C3E50"  # Dark blue
    - "#3498DB"  # Light blue
    - "#E74C3C"  # Red accent
  secondary_colors:
    - "#ECF0F1"  # Light Gray
    - "#95A5A6"  # Medium Gray
  typography:
    headings: "Open Sans"
    body: "Roboto"
  tone: "Professional and trustworthy"
  values:
    - "Expertise"
    - "Reliability"
    - "Innovation"

# Tool Configuration
tools:
  analysis:
    - "WebAnalyzer"
  design:
    - "DesignResearch"
  development:
    - "CodeGenerator"
    - "Deployment"
  content:
    - "ContentAnalyzer"
  testing:
    - "WebAnalyzer" 